spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001

spring:
  application:
    name: microservicecloud-config-eureka-client
  profiles: dev

eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001
spring:
  application:
    name: microservicecloud-config-eureka-client
  profiles: test
eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/